name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: CI
      run: nix-shell shell.nix --run 'make setup-git-for-github submodules test-via-docker'
