name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix
    steps:
    - uses: actions/checkout@v2
    - uses: textbook/git-checkout-submodule-action@master
    - name: CI
      run: nix-shell shell.nix --run 'make rust-setup test'
